/**
 * UI wording in both languages.
 *
 * Card, joker, voucher and deck names stay English throughout: those are the
 * words printed on the screen the player is looking at, and translating them
 * would make the app harder to use, not easier. Poker hand names are the same
 * case — Balatro shows "Flush", so this app says "Flush".
 *
 * The advice text itself is generated by the engine and is still English only.
 * Those strings are built by interpolating game terms into sentences across six
 * engine modules, so keying them is its own piece of work rather than a
 * translation pass; `src/engine/` has no business importing a dictionary.
 */
export const LANGUAGES = ['en', 'de'] as const;
export type Language = (typeof LANGUAGES)[number];

const en = {
  appName: 'Bal-Track',
  language: 'Language',

  // Tabs and navigation
  tabRun: 'Run',
  tabShop: 'Shop',
  tabPack: 'Pack',
  tabHistory: 'History',
  runSections: 'Run sections',

  // Run setup
  newRun: 'New Run',
  deck: 'Deck',
  stake: 'Stake',
  startRun: 'Start Run',
  setupNote:
    'Deck and stake starting rules are applied automatically; you can still correct counters on the Run screen.',

  // Run overview
  undo: 'Undo',
  primaryHand: 'Hand you build around',
  primaryHandNone: 'Not decided yet',
  money: 'Money $',
  ante: 'Ante',
  jokerSlots: 'Joker slots',
  jokers: 'Jokers',
  vouchers: 'Vouchers',
  consumables: 'Consumables',
  addJoker: 'Add joker…',
  addVoucher: 'Add redeemed voucher…',
  addConsumable: 'Add consumable…',
  sell: 'Sell',
  cannotSell: 'Cannot sell',
  eternalCannotBeSold: 'Eternal jokers cannot be sold',
  moveLeft: 'move {name} left',
  moveRight: 'move {name} right',
  editionOf: '{name} edition',
  used: 'Used',
  usePlanet: 'Use (+1 level)',
  runWon: 'Run won',
  runLost: 'Run lost',
  abandonRun: 'Abandon run',
  confirmWon: 'End this run as WON?',
  confirmLost: 'End this run as LOST?',
  confirmAbandon: 'Abandon this run without recording a result? It will not appear in your history.',

  // Corrections
  corrections: 'Corrections',
  correctionsNote:
    'The app books these itself from vouchers, planets and used consumables. Adjust them only when your run has drifted from what it recorded.',
  handsPerRound: 'Hands per round',
  discardsPerRound: 'Discards per round',
  handLevel: '{hand} level',

  // Deck profile
  deckProfile: 'Deck profile',
  erraticNote: 'Erratic deck — check these numbers against your actual starting deck.',
  faceCards: 'Face cards',
  deckSize: 'Deck size',
  hearts: 'Hearts',
  diamonds: 'Diamonds',
  spades: 'Spades',
  clubs: 'Clubs',
  bonus: 'Bonus',
  mult: 'Mult',
  wild: 'Wild',
  glass: 'Glass',
  steel: 'Steel',
  stone: 'Stone',
  gold: 'Gold',
  lucky: 'Lucky',

  // Stickers
  jokerStickers: 'Joker stickers',
  eternal: 'Eternal',
  perishable: 'Perishable',
  rental: 'Rental',

  // Shop
  rerollCost: 'Reroll $',
  cardsOnOffer: 'Cards on offer',
  addShopCard: 'Add shop card…',
  voucher: 'Voucher',
  addShopVoucher: 'Add voucher…',
  boosterPacks: 'Booster packs',
  addPack: 'Add pack…',
  screenshotRead: 'Read a screenshot…',
  screenshotReading: 'Reading…',
  screenshotNothing: 'No cards found in that screenshot.',
  screenshotFailed: 'That screenshot could not be read.',
  screenshotOnOffer: 'on offer',
  screenshotInRun: 'in the run',
  screenshotWhere: 'Where {name} belongs',
  screenshotNoSlots: '{count} did not fit: no free joker slot.',
  screenshotSkipped: '{count} more found that do not belong on this tab.',
  screenshotAdd: 'Add ticked cards',
  whichCard: 'Which card?',
  packHint: 'Bought a pack? Enter its contents on the Pack tab for pick advice.',
  bought: 'Bought',
  redeemed: 'Redeemed',
  rerolled: 'Rerolled',
  clearShop: 'Clear shop',
  advice: 'Advice',
  noRoom: 'No free slot',
  notAffordable: 'Not affordable',
  baseVoucherMissing: 'Base voucher not redeemed',
  removeX: 'remove {name}',
  removeVoucher: 'remove voucher',
  price: '$',

  // Pack
  packType: 'Pack type',
  optionsInPack: 'Options in the pack',
  addPackOption: 'Add pack option…',
  clear: 'Clear',
  take: 'Take',

  // Advice list
  adviceEmpty: 'Add shop items above to get advice.',
  notAvailable: 'not available',
  baselineNote: 'the baseline everything else is measured against',
  scoreSuffix: 'score',
  costs: 'costs',
  evidenceModeled: 'computed',
  evidencePartial: 'part computed',
  evidenceHeuristic: 'rated',

  // Score panel
  typicalHand: 'Typical {hand} ~{score}',
  anteTargets: 'Ante {ante} targets {small} / {big} / {boss}',
  notCounted: 'Not counted: {names}',
  doesNotFire: 'Does not fire on {hand}: {names}',
  andMore: '{names} +{count} more',

  // Strategy
  strategy: 'Strategy',
  open: 'Open — stay flexible',
  leaning: 'Leaning',
  commit: 'Commit',
  lookFor: 'Look for:',
  otherOptions: 'Other options',

  // Joker order
  orderFine: 'Joker order looks good — jokers trigger left to right.',
  applyOrder: 'Apply suggested order',

  // Suit prompt
  bookConversion: 'Book conversion',
  skipAdjustManually: 'Skip (adjust manually)',
  convertingTo: '{name}: converting {done}/3 cards to {suit}. Tap the source suits:',
  fromSuit: 'from {suit}',

  packStandardNote:
    'Standard packs contain playing cards, which bal-track does not evaluate individually. Rule of thumb: take cards with seals, editions or enhancements that fit your build; otherwise skipping is fine.',
  took: 'Took {name}',
  noFreeSlotNote: 'No free joker slot — sell a joker on the Run tab before taking {name}.',
  addedToJokers: '{name} added to your jokers.',
  planetUsedNote: '{name} used — hand level raised.',
  theSoulNote: 'The Soul! Add your new legendary joker on the Run tab.',
  tellSuitsNote: '{name} — tell me which suits it converted.',
  profileUpdatedNote: '{name} — deck profile updated.',
  notTrackedNote: '{name} — not tracked automatically, adjust the deck profile if needed.',

  // History
  noFinishedRuns: 'No finished runs yet.',
  pastRuns: 'Past runs',
  clearHistory: 'Clear history',
  confirmClearHistory: 'Delete all {runs} finished runs? This cannot be undone once you start a new run.',
  historySummary: '{runs} runs · {wins} wins · {rate}% win rate',
  won: 'won',
  lost: 'lost',
} as const;

/** Every key must exist in every language, so a missing translation is a type error. */
type Phrases = Record<keyof typeof en, string>;

const de: Phrases = {
  appName: 'Bal-Track',
  language: 'Sprache',

  tabRun: 'Run',
  tabShop: 'Shop',
  tabPack: 'Pack',
  tabHistory: 'Verlauf',
  runSections: 'Bereiche des Runs',

  newRun: 'Neuer Run',
  deck: 'Deck',
  stake: 'Stake',
  startRun: 'Run starten',
  setupNote:
    'Die Startregeln von Deck und Stake werden automatisch angewendet; korrigieren kannst du sie weiterhin auf dem Run-Bildschirm.',

  undo: 'Rückgängig',
  primaryHand: 'Hand, auf die du spielst',
  primaryHandNone: 'Noch nicht entschieden',
  money: 'Geld $',
  ante: 'Ante',
  jokerSlots: 'Joker-Plätze',
  jokers: 'Joker',
  vouchers: 'Vouchers',
  consumables: 'Consumables',
  addJoker: 'Joker hinzufügen…',
  addVoucher: 'Eingelösten Voucher hinzufügen…',
  addConsumable: 'Consumable hinzufügen…',
  sell: 'Verkaufen',
  cannotSell: 'Unverkäuflich',
  eternalCannotBeSold: 'Eternal-Joker lassen sich nicht verkaufen',
  moveLeft: '{name} nach links',
  moveRight: '{name} nach rechts',
  editionOf: 'Edition von {name}',
  used: 'Benutzt',
  usePlanet: 'Benutzt (+1 Level)',
  runWon: 'Run gewonnen',
  runLost: 'Run verloren',
  abandonRun: 'Run verwerfen',
  confirmWon: 'Diesen Run als GEWONNEN beenden?',
  confirmLost: 'Diesen Run als VERLOREN beenden?',
  confirmAbandon: 'Diesen Run ohne Ergebnis verwerfen? Er taucht nicht im Verlauf auf.',

  corrections: 'Korrekturen',
  correctionsNote:
    'Die App bucht das selbst aus Vouchers, Planeten und benutzten Consumables. Nachbessern nur, wenn dein Run von dem abweicht, was hier steht.',
  handsPerRound: 'Hände pro Runde',
  discardsPerRound: 'Discards pro Runde',
  handLevel: 'Level von {hand}',

  deckProfile: 'Deck-Profil',
  erraticNote: 'Erratic Deck — prüfe diese Zahlen gegen dein tatsächliches Startdeck.',
  faceCards: 'Bildkarten',
  deckSize: 'Deckgröße',
  hearts: 'Herz',
  diamonds: 'Karo',
  spades: 'Pik',
  clubs: 'Kreuz',
  bonus: 'Bonus',
  mult: 'Mult',
  wild: 'Wild',
  glass: 'Glas',
  steel: 'Stahl',
  stone: 'Stein',
  gold: 'Gold',
  lucky: 'Lucky',

  jokerStickers: 'Joker-Sticker',
  eternal: 'Eternal',
  perishable: 'Perishable',
  rental: 'Rental',

  rerollCost: 'Reroll $',
  cardsOnOffer: 'Karten im Angebot',
  addShopCard: 'Shop-Karte hinzufügen…',
  voucher: 'Voucher',
  addShopVoucher: 'Voucher hinzufügen…',
  boosterPacks: 'Booster-Packs',
  addPack: 'Pack hinzufügen…',
  screenshotRead: 'Screenshot einlesen…',
  screenshotReading: 'Lese…',
  screenshotNothing: 'In dem Screenshot wurden keine Karten gefunden.',
  screenshotFailed: 'Der Screenshot konnte nicht gelesen werden.',
  screenshotOnOffer: 'im Angebot',
  screenshotInRun: 'im Besitz',
  screenshotWhere: 'Wohin {name} gehört',
  screenshotNoSlots: '{count} passten nicht: kein freier Joker-Platz.',
  screenshotSkipped: '{count} weitere gefunden, die nicht in diesen Tab gehören.',
  screenshotAdd: 'Angehakte übernehmen',
  whichCard: 'Welche Karte?',
  packHint: 'Pack gekauft? Trag den Inhalt im Pack-Tab ein, dann gibt es Empfehlungen zur Auswahl.',
  bought: 'Gekauft',
  redeemed: 'Eingelöst',
  rerolled: 'Gererollt',
  clearShop: 'Shop leeren',
  advice: 'Empfehlung',
  noRoom: 'Kein freier Platz',
  notAffordable: 'Nicht bezahlbar',
  baseVoucherMissing: 'Basis-Voucher nicht eingelöst',
  removeX: '{name} entfernen',
  removeVoucher: 'Voucher entfernen',
  price: '$',

  packType: 'Pack-Typ',
  optionsInPack: 'Karten im Pack',
  addPackOption: 'Karte aus dem Pack hinzufügen…',
  clear: 'Leeren',
  take: 'Nimm',

  adviceEmpty: 'Trag oben Shop-Karten ein, dann gibt es eine Empfehlung.',
  notAvailable: 'nicht möglich',
  baselineNote: 'die Basislinie, an der alles andere gemessen wird',
  scoreSuffix: 'Punkte',
  costs: 'kostet',
  evidenceModeled: 'gerechnet',
  evidencePartial: 'teils gerechnet',
  evidenceHeuristic: 'geschätzt',

  typicalHand: 'Typisch {hand} ~{score}',
  anteTargets: 'Ante {ante} verlangt {small} / {big} / {boss}',
  notCounted: 'Nicht mitgerechnet: {names}',
  doesNotFire: 'Löst bei {hand} nicht aus: {names}',
  andMore: '{names} +{count} weitere',

  strategy: 'Strategie',
  open: 'Offen — bleib flexibel',
  leaning: 'Tendenz',
  commit: 'Festgelegt',
  lookFor: 'Halt Ausschau nach:',
  otherOptions: 'Andere Möglichkeiten',

  orderFine: 'Joker-Reihenfolge passt — Joker lösen von links nach rechts aus.',
  applyOrder: 'Vorgeschlagene Reihenfolge übernehmen',

  bookConversion: 'Umwandlung buchen',
  skipAdjustManually: 'Überspringen (von Hand nachtragen)',
  convertingTo: '{name}: {done}/3 Karten werden zu {suit}. Tippe die Ausgangsfarben an:',
  fromSuit: 'von {suit}',

  packStandardNote:
    'Standard-Packs enthalten Spielkarten, die bal-track nicht einzeln bewertet. Faustregel: Karten mit Seals, Editionen oder Enhancements nehmen, die zu deinem Build passen; sonst ist Überspringen in Ordnung.',
  took: '{name} genommen',
  noFreeSlotNote: 'Kein freier Joker-Platz — verkauf erst einen Joker im Run-Tab, bevor du {name} nimmst.',
  addedToJokers: '{name} zu deinen Jokern hinzugefügt.',
  planetUsedNote: '{name} benutzt — Handlevel erhöht.',
  theSoulNote: 'The Soul! Trag deinen neuen legendären Joker im Run-Tab ein.',
  tellSuitsNote: '{name} — sag mir, welche Farben umgewandelt wurden.',
  profileUpdatedNote: '{name} — Deck-Profil aktualisiert.',
  notTrackedNote: '{name} — wird nicht automatisch erfasst, pass bei Bedarf das Deck-Profil an.',

  noFinishedRuns: 'Noch keine beendeten Runs.',
  pastRuns: 'Frühere Runs',
  clearHistory: 'Verlauf leeren',
  confirmClearHistory: 'Alle {runs} beendeten Runs löschen? Sobald du einen neuen Run startest, lässt sich das nicht mehr rückgängig machen.',
  historySummary: '{runs} Runs · {wins} gewonnen · {rate}% Siegquote',
  won: 'gewonnen',
  lost: 'verloren',
};

export const DICTIONARY: Record<Language, Phrases> = { en, de };
export type PhraseKey = keyof typeof en;

/** Fills `{name}` style placeholders. Missing values are left as-is, not blanked. */
export function interpolate(text: string, values?: Record<string, string | number>): string {
  if (!values) return text;
  return text.replace(/\{(\w+)\}/g, (whole, key: string) =>
    (key in values ? String(values[key]) : whole));
}
